### PR TITLE
bump to Lean version 4.9.0

### PR DESCRIPTION
**Pull request by MAO3J1m0Op**
Test these changes locally–make sure everything still works as intended. Check `lake build`, `leanblueprint`, and try to build the documentation. The more that this is tested, the better.

### CODE REVIEW

**Comment by Stavan-Jain** [comment]
After running `lake clean` followed by `lake exe cache get`, I get the following warning:

image

and then `lake build` fails with the following error message:

image

**Comment by MAO3J1m0Op** [comment]
Try deleting `.lake`, or running `lake update` in between the two commands you ran.

**Comment by Stavan-Jain** [comment]
everything works for me now after deleting .lake

**Review by MithicSpirit — APPROVED** [review]
lgtm

**Review by Stavan-Jain — APPROVED** [review]

**Comment by Anoushka1406** [comment]
slay

**Review by Anoushka1406 — APPROVED** [review]
slay

**Review by william11339 — APPROVED** [review]

**Pull request merged**
