### PR TITLE
lists financial support sources for project

### LINKED ISSUE #44: List NSF grants that supported the project
This project was supported in part by some NSF grants, the IDs of which will be communicated to us by the leaders of Duke Math+. We will add this information to `README.md` once we are made known of the specifics.

### PR DESCRIPTION
**Pull request by Stavan-Jain**

### CODE REVIEW

**Review by MAO3J1m0Op — APPROVED** [review]
I'd say "supported in part by". Otherwise looks good.

I'd ask that we wait to merge this until I've filled in the `sorry`s that are pending on chapter 3. I'm working on that right now; should be done by the end of the week.

**Review by dominicking7 — APPROVED** [review]
lgtm

**Review by MithicSpirit — APPROVED** [review]
lgtm

**Comment by Stavan-Jain** [comment]
> I'd say "supported in part by". Otherwise looks good.

Aren't we financially supported by the three listed sources only?

**Comment by MAO3J1m0Op** [comment]
> > I'd say "supported in part by". Otherwise looks good.
> 
> Aren't we financially supported by the three listed sources only?

I suppose so. I stand corrected.

**Comment by MAO3J1m0Op** [comment]
Waiting to merge until #46 is resolved.

**Pull request merged**
