### PR TITLE
disable `unusedTactic` linter for every file

### PR DESCRIPTION
**Pull request by MAO3J1m0Op**
Fixes `build-strict` issue in chapter 0. This is meant to be a temporary fix until a solution for disabling this linter globally becomes known.

### CODE REVIEW

**Review by Stavan-Jain — APPROVED** [review]
lgtm

**Comment by Stavan-Jain** [comment]
Actually, it may be a good idea all at once (i.e. for every file in all worlds) once everything is merged

**Comment by MAO3J1m0Op** [comment]
> Actually, it may be a good idea all at once (i.e. for every file in all worlds) once everything is merged

On paper, I think that idea is sound, but doing that completely undermines our CI/CD (plus I don’t like big red X’s).

I think it’s fine to do this not great fix in all our chapters, and then remove it later when we have a better solution. To me, the problem this creates isn’t as bad as the one it solves.

**Comment by Stavan-Jain** [comment]
Okay! That makes sense to me

**Review by chenne19 — APPROVED** [review]

**Pull request merged**
