### PR TITLE
Create NOTICE

### PR DESCRIPTION
**Pull request by william11339**
I just drafted up a notice file, but I'm not a lawyer so please lmk if anything looks wrong

### CODE REVIEW

**Comment by MithicSpirit** [comment]
I think it'd be better to just include this information in the README (#39). A lot of it is already there anyway.

**Comment by william11339** [comment]
It did feel pretty redundant so I'll leave it up to everyone. 
Looking over the license what we actually need to do is add the boilerplate declaration at the top of every sheet and the NOTICE file is to make everything explicitly clear, so I figured the NOTICE was an easy middle ground.

**Review by Anoushka1406 — APPROVED** [review]
Im okay either way, but I do think there's no harm in including this

**Comment by MithicSpirit** [comment]
> It did feel pretty redundant so I'll leave it up to everyone. Looking over the license what we actually need to do is add the boilerplate declaration at the top of every sheet and the NOTICE file is to make everything explicitly clear, so I figured the NOTICE was an easy middle ground.

The advantage of doing adding the declaration to each file is that we could provide individual attribution to the authors of the file. Note that the given boilerplate declaration doesn't have to be used, and we can write our own. Mathlib does it pretty nicely imo.

**Pull request closed without merging**
