### PR TITLE
set up editor configuration files

### PR DESCRIPTION
**Pull request by MithicSpirit**
Creates a `.vscode/settings.json` for VSCode (and the like) users and a
`.editorconfig` for everyone else.

### CODE REVIEW

**Comment by MithicSpirit** [comment]
Please do some testing as I haven't really tested this outside of Neovim.

**Review by MAO3J1m0Op — APPROVED** [review]
Can't speak to `.editorconfig`, but lgtm otherwise

**Review by Stavan-Jain — APPROVED** [review]
Works for me!

**Review by 4rim — APPROVED** [review]
works for both neovim and emacs

**Pull request merged**
